from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *



class CustomerEntry(QWidget):
    def __init__(self, parent=None):
        super(CustomerEntry, self).__init__(parent)

        self.resize(1024, 768)
        self.centralWidget = QWidget(self)
        self.tableWidget = QTableWidget(self.centralWidget)
        self.tableWidget.setGeometry(QRect(70, 160, 591, 181))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.CurrentChanged|QAbstractItemView.EditKeyPressed)
        self.tableWidget.setRowCount(6)
        self.tableWidget.setColumnCount(1)
        item = QTableWidgetItem()
        item.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        item.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        item.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        item.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        item.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        item.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setKerning(False)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(500)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.comboBox = QComboBox(self.centralWidget)
        self.comboBox.setGeometry(QRect(840, 90, 91, 31))
        font = QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        firstnameitem = self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.btn_back = QPushButton(self.centralWidget)
        self.btn_back.setGeometry(QRect(200, 580, 91, 51))
        font = QFont()
        font.setPointSize(24)
        self.btn_back.setFont(font)
        self.btn_next = QPushButton(self.centralWidget)
        self.btn_next.setGeometry(QRect(890, 580, 91, 51))
        font = QFont()
        font.setPointSize(24)
        self.btn_next.setFont(font)
        self.tableWidget_2 = QTableWidget(self.centralWidget)
        self.tableWidget_2.setGeometry(QRect(770, 90, 71, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(1)
        item = QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_3 = QTableWidget(self.centralWidget)
        self.tableWidget_3.setGeometry(QRect(70, 100, 381, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(1)
        item = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(500)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget_2.raise_()
        self.tableWidget.raise_()
        self.comboBox.raise_()
        self.btn_back.raise_()
        self.btn_next.raise_()
        self.tableWidget_3.raise_()
        # CustomerEntry.setCentralWidget(self.centralWidget)



        _translate = QCoreApplication.translate
        self.setWindowTitle(_translate("CustomerEntry", "CustomerEntry"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("CustomerEntry", "First Name"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("CustomerEntry", "Last Name"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("CustomerEntry", "Address 1"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("CustomerEntry", "Address 2"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("CustomerEntry", "City"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("CustomerEntry", "Zip Code"))
        self.comboBox.setItemText(0, _translate("CustomerEntry", "Default"))
        self.comboBox.setItemText(1, _translate("CustomerEntry", "Residence"))
        self.comboBox.setItemText(2, _translate("CustomerEntry", "Business"))
        self.comboBox.setItemText(3, _translate("CustomerEntry", "Hotel"))
        self.comboBox.setItemText(4, _translate("CustomerEntry", "School"))
        self.btn_back.setText(_translate("CustomerEntry", "Back"))
        self.btn_next.setText(_translate("CustomerEntry", "Next"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("CustomerEntry", "Presets:"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("CustomerEntry", "Phone"))


